---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-debian12}-ansible:latest"
    pre_build_image: true
    privileged: true # To run systemd inside image
    cgroupns_mode: host # Required for cgroup v2 hosts
    volumes: # To run systemd inside image
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    command: null # Use the default image's CMD.
provisioner:
  name: ansible
verifier:
  name: testinfra
